### ISSUE TITLE
Roundabouts are considerer as road

### ISSUE THREAD

**Issue by costales** [valhalla/mjolnir#310] opened 2015-10-23 13:49 UTC
Hi!
In this roundabout, the Valhalla type is not a roundabout.

Screenshot:
![roundabout](https://cloud.githubusercontent.com/assets/5886786/10694197/25288bba-799d-11e5-82d6-d604765127c2.jpg)

URL to OSM:
https://www.openstreetmap.org/edit?editor=potlatch2#map=19/43.32618/-5.73105

Thanks a lot in advance!

**Comment by dgearhart** [comment] 2015-10-23 14:58
@costales - it appears the issue is because it is marked as a motorway_link and roundabout - looking to update logic to handle properly

**Closed** 2015-10-27 12:20 UTC

**Comment by dgearhart** [comment] 2015-11-04 14:10
@costales - the roundabout fixes are in production

**Comment by costales** [comment] 2015-11-05 07:51
Hi! I think all works perfect now. If I see anything wrong I will tell you.
Thanks a lot for your support!!



-- 
Enviado con Dekko desde mi dispositivo Ubuntu
